@startuml
left to right direction
skinparam packageStyle rectangle

actor Student
actor Administrator

rectangle "Smart Campus Study Room Booking System" {
    usecase "View Room Availability" as UC1
    usecase "US-01: View room availability" as UC1
    usecase "US-02: Book a study room" as UC2
    usecase "US-03: Cancel booking" as UC3
    usecase "US-04: Receive booking confirmation" as UC4
    usecase "US-05: Review room usage" as UC5
    usecase "US-06: Block or unblock room" as UC6

    ' Include relationship justified by Rule R4 & US-04
    UC2 ..> UC4 : <<include>>
}

Student --> UC1
Student --> UC2
Student --> UC3

Administrator --> UC5
Administrator --> UC6

@enduml